### ISSUE TITLE
sunshine and wind_gust_direction are NULL

### ISSUE THREAD

**Issue by tawissus** [jdemaeyer/brightsky#133]
I wanted to work with sunshine data today. 
Unfortunately, sun and the wind direction are always NULL (eg in Berlin). 
Is it a bug or is it not available in some locations?

eg Berlin lat 52.54 / lon 13.54

**Comment by jdemaeyer** [comment]
Hi @tawissus,

while sunshine duration is indeed not measured at too many stations (and for your location in particular, the issue arises because Berlin-Tempelhof recently stopped recording it), it should still be available through Bright Sky. I.e. yes this _is_ a bug, thanks for pointing this out! :)

I'm currently on vacation and won't have time to fix this for the next two weeks. As a work-around, you can [supply ` dwd_station_id=00403`](https://api.brightsky.dev/weather?date=2022-11-03&dwd_station_id=00403) instead of `lat` and `lon` to the `/weather` endpoint. This will get you records from the Berlin-Dahlem station, which measures `sunshine`. ([Here](https://opendata.dwd.de/climate_environment/CDC/observations_germany/climate/hourly/sun/recent/SD_Stundenwerte_Beschreibung_Stationen.txt) is the list of stations which record `sunshine`, you can find the DWD station ID in the first column and the date of the latest record in the third column.)

As a note to myself I'm sketching two approaches here:

1. Check how many stations actually have `null` sunshine values during nighttime and non-`null` values during daytime, maybe we can remove `sunshine` from the [ignored missing fields](https://github.com/jdemaeyer/brightsky/blob/master/brightsky/query.py#L78) setting?
2. Add a `must_include` parameter to `/weather` which allows (partially) overriding that setting

**Comment by tawissus** [comment]
Thank you very much.
Have a nice vacation

**Comment by jdemaeyer** [comment]
Thanks! :)


> 1. Check how many stations actually have `null` sunshine values during nighttime and non-`null` values during daytime, maybe we can remove `sunshine` from the [ignored missing fields](https://github.com/jdemaeyer/brightsky/blob/master/brightsky/query.py#L78) setting?

```
postgres=# select * from (
postgres=#   select
postgres=#     source_id,
postgres=#     count(sunshine) as available,
postgres=#     count(*) - count(sunshine) as missing
postgres=#   from weather
postgres=#   where timestamp between '2022-11-04' and '2022-11-04 23:55'
postgres=#   group by source_id
postgres=# ) _
postgres=# where
postgres=#   available > 0 and
postgres=#   missing > 0
postgres=# ;

 source_id | available | missing
-----------+-----------+---------
(0 rows)
```

Looks like we can just go ahead and just drop `sunshine` from `IGNORED_MISSING_FIELDS`, particularly now that we have #129.

**Comment by jdemaeyer** [comment]
24c403c

**Comment by jdemaeyer** [comment]
@tawissus I've adjusted our mechanism which fills up incomplete weather records (like the ones from Berlin-Marzahn, which is the nearest station for your coordinates), and all regular lat/lon-based requests should now include values for `sunshine` again.

Missing values for `wind_gust_direction` stem from a different bug which I've added a ticket for here: #134

I'm closing this, but feel free to re-open if you think the issue with `sunshine` still exists :)

**Comment by jdemaeyer** [comment]
This change seems to have had a tangible impact on performance. I'll keep it in for now but am re-opening the issue to remind myself to look deeper into it once I'm back from vacation.

![Average response time increasing significantly after this change hit production](https://user-images.githubusercontent.com/10531844/200887103-ef1ec890-8478-4b6b-9bbc-22916f245175.png)

**Comment by tawissus** [comment]
Hey, thanks for your effort! 
I now have the sunshine in the JSON. 
But now please enjoy the vacation!

**Comment by jdemaeyer** [comment]
Thanks for the confirmation, I'm glad the fix worked :)

The slightly heightened average response time seems to have been a transient effect, so I'm closing this issue:

![image](https://user-images.githubusercontent.com/10531844/201513495-f957c1f5-2715-4f15-97e2-b4539c21f133.png)

**Comment by SB-511** [comment]
Hi @jdemaeyer,

thanks for your work! 
I'm not sure if this is the right place to ask, but it seems to me that `wind_gust_direction` is always `null` for the current day. 

Example: 

    https://api.brightsky.dev/weather?lat=49.0&lon=8.4&date=2024-11-13&last_date=2024-11-15&max_dist=40000

returns a value for wind_gust_direction for every day up to when 2024-11-14 (today) starts:

```json
        {
            "timestamp": "2024-11-13T23:00:00+00:00",
            "source_id": 7197,
            "precipitation": 0.1,
            "pressure_msl": 1031.3,
            "sunshine": 0,
            "temperature": 4.5,
            "wind_direction": 220,
            "wind_speed": 6.8,
            "cloud_cover": 87,
            "dew_point": 3.7,
            "relative_humidity": 94,
            "visibility": 8490,
            "wind_gust_direction": 230,
            "wind_gust_speed": 12.2,
            "condition": "rain",
            "precipitation_probability": null,
            "precipitation_probability_6h": null,
            "solar": 0,
            "icon": "cloudy"
        },
        {
            "timestamp": "2024-11-14T00:00:00+00:00",
            "source_id": 6233,
            "precipitation": 0,
            "pressure_msl": 1031,
            "sunshine": 0,
            "temperature": 4.3,
            "wind_direction": 200,
            "wind_speed": 6.8,
            "cloud_cover": 88,
            "dew_point": 3.6,
            "relative_humidity": 95,
            "visibility": 8300,
            "wind_gust_direction": null,
            "wind_gust_speed": 13,
            "condition": "dry",
            "precipitation_probability": null,
            "precipitation_probability_6h": null,
            "solar": 0,
            "icon": "cloudy"
        },
```

Do you know the reason for this?

**Comment by SB-511** [comment]
(same thing seems to apply to `relative_humidity` for all timesteps that are in the future (= forecasts))

**Comment by jdemaeyer** [comment]
Hi @SB-511, thanks for reaching out! These are indeed known (and admittedly poorly documented) limitations that we inherit from the DWD data. The MOSMIX forecast contains neither `relative_humidity` nor `wind_gust_direction`, the current-day measurements do not contain `wind_gust_direction`.
