### ISSUE TITLE
Make API available for http

### ISSUE THREAD

**Issue by AlexW987** [jdemaeyer/brightsky#167]
My home automation system doesnt support https so it cannot use the API

**Comment by jdemaeyer** [comment]
Ah, yes, I've never bothered to enable this because all `.dev` domains are on the HTTP Strict-Transport-Security (HSTS) preload list, i.e. HTTP clients (or, I guess, _browsers_) are supposed to only allow HTTPS connections to these domains. But when your system does not even support HTTPS, I highly doubt it cares about Strict-Transport-Security policies :sweat_smile:. I've [adjusted the server configuration to include insecure HTTP](https://github.com/jdemaeyer/brightsky-infrastructure/commit/60d4a963f04442338068ad40ecb44fc893ee1687), please try again now!

**Comment by AlexW987** [comment]
Works like a charm now. Thanks for the quick fix
