### ISSUE TITLE
Lots of null values, while the spec says it should be number

### ISSUE THREAD

**Issue by mweinelt** [jdemaeyer/brightsky#92]
https://api.brightsky.dev/weather?lat=49.8&lon=8.6&date=2020-07-22&laste_date=2020-07-23

This started happening around 2020-07-22 15:49 CEST.

```json
{
  "weather": [
    {
      "timestamp": "2020-07-22T00:00:00+00:00",
      "source_id": 16264,
      "precipitation": 0,
      "pressure_msl": null,
      "sunshine": null,
      "temperature": 10.7,
      "wind_direction": null,
      "wind_speed": null,
      "cloud_cover": null,
      "dew_point": 7.3,
      "relative_humidity": 80,
      "visibility": null,
      "wind_gust_direction": null,
      "wind_gust_speed": null,
      "condition": null,
      "icon": "clear-night"
    }
  ]
}
```

**Comment by mweinelt** [comment]
Closing in favor of #93.

**Comment by jdemaeyer** [comment]
Thanks for raising this. I agree this is likely caused by the same underlying issue as #93, namely that we have a lot of `condition = null` rows in the database while the worker re-parses the necessary files after deploying v0.9.6. Our fallback mechanism (the Darmstadt station you posted above never records all fields) gets thrown off by this because it cannot find a nearby station with a nonzero `condition`.

In your case I suspect this should be fine again once the DWD publishes updated `current` files in about ten to fifteen minutes.
